<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kom"
 *
 * Auto generated by Extension Builder 2017-05-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Kandidat-O-Mat',
    'description' => 'Kandidat-O-Mat',
    'category' => 'plugin',
    'author' => 'Kevin Ulrich Moschallski',
    'author_email' => 'info@digitalpatrioten.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.7.0-DEV',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
